# Generated by Django 3.0.6 on 2020-09-07 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='lname',
        ),
        migrations.AlterField(
            model_name='moderator',
            name='facebook',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AlterField(
            model_name='moderator',
            name='instagram',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AlterField(
            model_name='moderator',
            name='linkedIn',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AlterField(
            model_name='moderator',
            name='totalFollowers',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='moderator',
            name='totalLikes',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='moderator',
            name='totalPosts',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='moderator',
            name='twitter',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AlterField(
            model_name='moderator',
            name='whatsapp',
            field=models.CharField(default='tel:+2348 112 659 304', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
