# Generated by Django 3.0.6 on 2020-09-07 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200907_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='visitor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Visitor'),
        ),
    ]
