# Generated by Django 3.0.6 on 2020-09-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200909_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(default='Web Development', max_length=200),
            preserve_default=False,
        ),
    ]
