# Generated by Django 3.0.6 on 2020-09-11 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200911_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moderator',
            name='visitor',
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Moderator'),
        ),
    ]
